### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by GinBlades** [GinBlades/CustomAuth#1]
- [x] Remove encryption from hashing (1)
- [x] Use DataProtection API
- [ ] Automatically hash before save on password field.
- [x] Allow Google log in
- [ ] Save Google user to database
- [ ] Add identity after Google user has been established.

1. Encryption before hashing is not recommended ([Explanation on SO](http://security.stackexchange.com/questions/45344/is-it-useful-to-protect-hashed-password-with-encryption)). Basically, it's considered more likely the application would be compromised than the database. If you encrypt and hash, you have to have a strategy to handle the key being compromised.
2. [SO Question](http://stackoverflow.com/questions/6677160/in-entity-framework-how-to-call-a-method-on-entity-before-saving). [MSDN Article](https://msdn.microsoft.com/en-us/library/cc716714.aspx)
